
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-13
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-13
pull_requests: [{"author":{"id":"U_kgDOCyANAw","is_bot":false,"login":"Joaquin-Wong","name":""},"headRefName":"jw-dashboard-button","number":63,"title":"Jw dashboard button","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-13/pull/63"},{"author":{"id":"MDQ6VXNlcjYyMzExNjU3","is_bot":false,"login":"AryaSadeghi21","name":"Arya Sadeghi"},"headRefName":"as-add-recordcommonstats-launcher","number":61,"title":"as - added launcher for recordcommonstats","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-13/pull/61"},{"author":{"id":"U_kgDOCyANAw","is_bot":false,"login":"Joaquin-Wong","name":""},"headRefName":"jw-dashboard-placeholder","number":60,"title":"jw added placeholder page for dashboard with linking in App.jsx","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-13/pull/60"},{"author":{"id":"U_kgDOCVHkOQ","is_bot":false,"login":"nickkamenica","name":""},"headRefName":"common-features-api-endpoint","number":56,"title":"Add CommonsFeaturesController with GET /api/commonsfeatures endpoint","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-13/pull/56"},{"author":{"id":"U_kgDOCyANAw","is_bot":false,"login":"Joaquin-Wong","name":""},"headRefName":"jw-hiddencommons-apicontroller-v2","number":55,"title":"Hidden commons cannot buy or sell","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-13/pull/55"}]
